# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/chris/Projects/zynq_afgangsprojekt/Vivado/simple_adder/simple_adder.srcs/sources_1/bd/adder/ip/adder_add_0_2/adder_add_0_2.xci
# IP: The module: 'adder_add_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chris/Projects/zynq_afgangsprojekt/Vivado/simple_adder/simple_adder.srcs/sources_1/bd/adder/ip/adder_add_0_2/constraints/add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_add_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/chris/Projects/zynq_afgangsprojekt/Vivado/simple_adder/simple_adder.srcs/sources_1/bd/adder/ip/adder_add_0_2/adder_add_0_2.xci
# IP: The module: 'adder_add_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chris/Projects/zynq_afgangsprojekt/Vivado/simple_adder/simple_adder.srcs/sources_1/bd/adder/ip/adder_add_0_2/constraints/add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_add_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
