# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/adder/adder.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder || ORIG_REF_NAME==adder} -quiet] -quiet

# IP: bd/adder/ip/adder_add_0_2/adder_add_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_add_0_2 || ORIG_REF_NAME==adder_add_0_2} -quiet] -quiet

# IP: bd/adder/ip/adder_zynq_ultra_ps_e_0_3/adder_zynq_ultra_ps_e_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_zynq_ultra_ps_e_0_3 || ORIG_REF_NAME==adder_zynq_ultra_ps_e_0_3} -quiet] -quiet

# IP: bd/adder/ip/adder_ps8_0_axi_periph_1/adder_ps8_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_ps8_0_axi_periph_1 || ORIG_REF_NAME==adder_ps8_0_axi_periph_1} -quiet] -quiet

# IP: bd/adder/ip/adder_rst_ps8_0_100M_1/adder_rst_ps8_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_rst_ps8_0_100M_1 || ORIG_REF_NAME==adder_rst_ps8_0_100M_1} -quiet] -quiet

# IP: bd/adder/ip/adder_auto_ds_1/adder_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_auto_ds_1 || ORIG_REF_NAME==adder_auto_ds_1} -quiet] -quiet

# IP: bd/adder/ip/adder_auto_pc_1/adder_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_auto_pc_1 || ORIG_REF_NAME==adder_auto_pc_1} -quiet] -quiet

# XDC: bd/adder/adder_ooc.xdc
